language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
  - yarn lint
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
