language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
env:
  - PUBLIC_PATH='/reducks-starter/'
install:
  - npm install
script:
  - npm run test
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
