version: 2

jobs:
  setup:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Node version
          command: node -v
      - run:
          name: NPM version
          command: npm -v
      - restore_cache:
          name: Restore cached dependencies
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Cache dependencies
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:latest
    environment:
      - PUBLIC_PATH: ${PUBLIC_PATH}
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: junit.xml
      - persist_to_workspace:
          root: .
          paths:
            - coverage
            - junit.xml
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run linters
          command: npm run lint
  deploy:
    docker:
      - image: circleci/node:latest
    environment:
      - GH_NAME: ${GH_NAME}
      - GH_EMAIL: ${GH_EMAIL}
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to GitHub Pages
          command: npm run deploy -m "Deploy from CircleCI"

workflows:
  version: 2
  test_lint_build_deploy:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - setup
      - lint:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - setup
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - test
            - lint
      - deploy:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - build
