version: 2

jobs:
  setup:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Node version
          command: node -v
      - run:
          name: NPM version
          command: npm -v
      - run:
          name: Yarn version
          command: yarn -v
      - restore_cache:
          name: Restore cached dependencies
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Cache dependencies
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:latest
    environment:
      - PUBLIC_PATH: '/reducks-starter/'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test:ci
      - store_test_results:
          path: junit.xml
      - persist_to_workspace:
          root: .
          paths:
            - coverage
            - junit.xml
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run linters
          command: yarn lint

workflows:
  version: 2
  build_test_lint:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
