export const FETCH_REPOSITORIES_START = 'repositories/FETCH_REPOSITORIES_START';
export const FETCH_REPOSITORIES_SUCCESS = 'repositories/FETCH_REPOSITORIES_SUCCESS';
export const FETCH_REPOSITORIES_FAILURE = 'repositories/FETCH_REPOSITORIES_FAILURE';
export const CLEAR = 'repositories/CLEAR';
