name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        env:
          CI: true
        run: npm run test:ci
      - name: Build
        run: npm run build
